name: Deploy Aura Studio

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 143.110.167.193
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "index.html"
          target: "/var/www/theauraphotography"

      - name: Sync sang aura-studio
        uses: appleboy/ssh-action@master
        with:
          host: 143.110.167.193
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cp /var/www/theauraphotography/index.html /var/www/aura-studio/index.html
            echo "Deploy done: $(date)"
